import { inject, ref } from 'vue';
<template>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
  <div>Switch文档</div>
</template>

<script lang="ts">


export default {

}
</script>

<style lang="scss" scoped>

</style>